FROM nginx:1.27-alpine
COPY web /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
# config.json (DATA_BASE_URL) generowany przy starcie przez /docker-entrypoint.sh obrazu nginx.
COPY docker/web-entrypoint.sh /docker-entrypoint.d/40-web-config.sh
RUN chmod 755 /docker-entrypoint.d/40-web-config.sh
